/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    AgoraDaoFabric: {
      address:
        "0x7821aef99d107a284ef92278af975b2c122dea1e4b25fbf3a7917faf3b61147",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoFabric",
          interface_name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::agora_dao_fabric::structs::Dao",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "dao_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "description",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "category",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "image_URI",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "is_public",
              type: "core::bool",
            },
            {
              name: "creation_timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
          items: [
            {
              type: "function",
              name: "create_dao",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "description",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "category_ID",
                  type: "core::integer::u16",
                },
                {
                  name: "image_URI",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "is_public",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "dao_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_all_categories",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::byte_array::ByteArray>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_public_daos",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::agora_dao_fabric::structs::Dao>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::AgoraDaoFabric::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x17185bb589041a60c79918697f43e6b95cb6f7331e4358f44e81f3cb06feceb",
    },
    AgoraDao: {
      address:
        "0x2464ed1fd1c8010de56862eb67a2d0a2f1690529b8e675afd4779d938c0e657",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoImpl",
          interface_name: "contracts::agora_dao::IAgoraDao",
        },
        {
          type: "interface",
          name: "contracts::agora_dao::IAgoraDao",
          items: [
            {
              type: "function",
              name: "join_dao",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "fabric",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::integer::u256>",
          variants: [
            {
              name: "Some",
              type: "core::integer::u256",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::AgoraDao::GreetingChanged",
          kind: "struct",
          members: [
            {
              name: "greeting_setter",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_greeting",
              type: "core::byte_array::ByteArray",
              kind: "key",
            },
            {
              name: "premium",
              type: "core::bool",
              kind: "data",
            },
            {
              name: "value",
              type: "core::option::Option::<core::integer::u256>",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::AgoraDao::Event",
          kind: "enum",
          variants: [
            {
              name: "GreetingChanged",
              type: "contracts::agora_dao::AgoraDao::GreetingChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0xafdfbcbabcc4748bb223d99dba8c6e56c79c3b8d3bc5b7b7d1450f230e4998",
    },
  },
} as const;

export default deployedContracts;
