/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    AgoraDaoFabric: {
      address:
        "0x283deb31968ba57187eb9a7e5de348bb6b77f2eeca6f4840dd8416574bbb63",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoFabric",
          interface_name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::agora_dao_fabric::structs::Dao",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "dao_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "description",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "category",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "image_URI",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "is_public",
              type: "core::bool",
            },
            {
              name: "creation_timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
          items: [
            {
              type: "function",
              name: "create_dao",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "description",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "category_ID",
                  type: "core::integer::u16",
                },
                {
                  name: "image_URI",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "is_public",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "dao_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_all_categories",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::byte_array::ByteArray>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_public_daos",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::agora_dao_fabric::structs::Dao>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::AgoraDaoFabric::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x75d0ce6f454787165c255b58c58cd48a22275639998f82b4c0ff201083b282",
    },
    AgoraDao: {
      address:
        "0x67510aa793e3de0403712e691ff06450c5b63a8f0f10733e44835bc13082a72",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoImpl",
          interface_name: "contracts::agora_dao::IAgoraDao",
        },
        {
          type: "interface",
          name: "contracts::agora_dao::IAgoraDao",
          items: [
            {
              type: "function",
              name: "join_dao",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "fabric",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::events::UserJoined",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "user_ID",
              type: "core::integer::u16",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::AgoraDao::Event",
          kind: "enum",
          variants: [
            {
              name: "UserJoined",
              type: "contracts::agora_dao::events::UserJoined",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x4510dcdd01ccad861fb3ca71dd9f7e4efac445bef33d40405b5004c712ee0bb",
    },
  },
} as const;

export default deployedContracts;
