/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    AgoraDaoFabric: {
      address:
        "0x788e8d2a1fb646de11dc70be0718d27343ebc8cc52922be57faa51d0ebe683d",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoFabric",
          interface_name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::agora_dao_fabric::structs::Dao",
          members: [
            {
              name: "dao_ID",
              type: "core::integer::u16",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "dao_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "description",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "category",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "image_URI",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "is_public",
              type: "core::bool",
            },
            {
              name: "creation_timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::agora_dao_fabric::IAgoraDaoFabric",
          items: [
            {
              type: "function",
              name: "create_dao",
              inputs: [
                {
                  name: "name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "description",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "category_ID",
                  type: "core::integer::u16",
                },
                {
                  name: "image_URI",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "is_public",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "user_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "dao_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u16",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_all_categories",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::byte_array::ByteArray>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_public_daos",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::agora_dao_fabric::structs::Dao>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao_fabric::AgoraDaoFabric::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x342e0cac479f1a773252645756e179a3c8d7f5653b43b76011a2afdedc407e1",
    },
    AgoraDao: {
      address:
        "0x3c6bac38c80ab3237f76802e73bb4e4c3cc9eec419fe02a770543692e685a80",
      abi: [
        {
          type: "impl",
          name: "AgoraDaoImpl",
          interface_name: "contracts::agora_dao::IAgoraDao",
        },
        {
          type: "interface",
          name: "contracts::agora_dao::IAgoraDao",
          items: [
            {
              type: "function",
              name: "join_dao",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "fabric",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::integer::u256>",
          variants: [
            {
              name: "Some",
              type: "core::integer::u256",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::AgoraDao::GreetingChanged",
          kind: "struct",
          members: [
            {
              name: "greeting_setter",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_greeting",
              type: "core::byte_array::ByteArray",
              kind: "key",
            },
            {
              name: "premium",
              type: "core::bool",
              kind: "data",
            },
            {
              name: "value",
              type: "core::option::Option::<core::integer::u256>",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::agora_dao::AgoraDao::Event",
          kind: "enum",
          variants: [
            {
              name: "GreetingChanged",
              type: "contracts::agora_dao::AgoraDao::GreetingChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2d05f63ace143c69e65f9e6475724e84f8bd087bf6040eaa129492acb9a358e",
    },
  },
} as const;

export default deployedContracts;
